version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./media:/app/media
    env_file:
      - .env
    depends_on:
      - db
    command: ./startup.sh

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=friendsapp
    ports:
      - "5432:5432"

volumes:
  postgres_data:
